version: '3'

services:
  # Client
  app-1:
    extends:
      file: docker-compose.base.yml
      service: nx-app-base
    command: serve client 
    ports:
      - 3000:3000
    working_dir: /app/dist/apps

  # Server
  app-2:
    extends:
      file: docker-compose.base.yml
      service: nx-app-base
    command: node main.js
    ports:
      - ${PORT}:3333
      - ${WS_PORT}:8001
    working_dir: /app/dist/apps/server
    env_file:
      - .env

volumes:
  mono-node-modules: null
