version: '3'

services:
  # Client
  app-1:
    extends:
      file: docker-compose.base.yml
      service: nx-app-base
    command: serve client 
    ports:
      - 4201:4200
      - 3000:3000
    working_dir: /app/dist/apps

  # Server
  app-2:
    extends:
      file: docker-compose.base.yml
      service: nx-app-base
    command: node main.js
    ports:
      - 4202:3333
      - 8001:8001
    working_dir: /app/dist/apps/server

volumes:
  mono-node-modules: null
